plugins:
  - jekyll-paginate
  - jekyll-archives

paginate: 3
paginate_path: "/blog/:num/"

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "blog/post"
  - scope:
      path: ""
    values:
      layout: "default"

baseurl:
tagurl: /tag/

jekyll-archives:
  enabled: all
  layouts:
    year: blog/blogArchives/year-archive
    month: blog/blogArchives/month-archive
    day: blog/blogArchives/day-archive
    category: blog/blogArchives/category-archive
    tag: blog/blogArchives/tag-archive
